<a href="https://colab.research.google.com/github/seelamGayatri2006/2311CS020606/blob/main/feature_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import pandas as pd
# Load data
filename = "/content/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
print(dataframe)
# Split data into input (X) and output (Y)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

# Feature extraction
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)

# Print scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]
[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [ ]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
filename = "/content/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
# Feature extraction
model = LogisticRegression(max_iter=400)
rfe = RFE(estimator=model, n_features_to_select=3)
fit = rfe.fit(X, Y)


In [ ]:
fit.n_features_

3

In [ ]:
fit.support_

array([ True, False, False, False, False,  True,  True, False])

In [ ]:
fit.ranking_

array([1, 2, 4, 6, 5, 1, 1, 3])